name: Test

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - feature/*
      - bugfix/*

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  workflow_run:
    workflows: ["Build and Push"]
    types:
      - completed

  # Run tests for any PRs.
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/${{ github.repository }}/app.grocery_shopping:latest
      # options: --user vscode
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Pytest
        run: pytest